name: gist-update
on: push
jobs: 
  set-up-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "$(cat tree.txt)"
      - name: Update Gist
        run: 'gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /gists/0b68a2e2b1d0451f52c9dd96b3eb4f27 -f "files[tree.sh][content]=$(cat tree.sh)" -f "description=An updated gist description"'
